### ISSUE TITLE
Error:(3, 32) error: cannot find symbol class Secrets

### ISSUE THREAD

**Issue by panikajo** [steevp/UpdogFarmer#18]
C:\Users\panikajo\Downloads\UpdogFarmer\app\src\main\java\com\steevsapps\idledaddy\steam\SteamWebHandler.java
Error:(3, 32) error: cannot find symbol class Secrets
Error:(289, 75) error: cannot find symbol variable Secrets
Error:Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

**Comment by steevp** [comment]
Added in https://github.com/steevp/UpdogFarmer/commit/636c17c584f7e494199c1a54a0b5e8dff9a3ca66
